version: '2.2'
services:

    flux-postgres:
        image: postgres:9.6.12-alpine
        environment:
            - POSTGRES_PASSWORD=flux
        volumes:
            - ./sql:/docker-entrypoint-initdb.d
            - flux_pgdata:/var/lib/postgresql/data
        ports:
            - "5432:5432"

    flux-engine:
        image: flux-amd64-linux:latest
        environment:
            - STARTUP_SLEEP=${STARTUP_SLEEP:-60}
        volumes:
            - ./config/engine-config.properties:/home/user/flux/config/engine-config.properties

    flux-agent:
        image: flux-amd64-linux:latest
        environment:
            - RUN_AGENT="true"
            - STARTUP_SLEEP=${STARTUP_SLEEP:-60}
        volumes:
            - ./config/agent-config.properties:/home/user/flux/config/agent-config.template

    flux-console:
        image: flux-amd64-linux:latest
        environment:
            - RUN_CONSOLE="true"
            - STARTUP_SLEEP=${STARTUP_SLEEP:-60}
        volumes:
            - ./config/opsconsole8.properties:/home/user/.flux/opsconsole8.properties
        ports:
            - "7186:7186"

    # flux-pgdata:
    #     image: busybox
    #     volumes:
    #     - ./pgdata:/bitnami
    #     command: ["sh", "-c", "chown -R 1001:1001 /bitnami"]

volumes:
    flux_pgdata:

