CREATE TABLE FLUX_ACTION (PK BIGINT NOT NULL PRIMARY KEY, CLAZZ CHARACTER VARYING(200) NOT NULL, FLOW_CHART BIGINT NOT NULL, NAME CHARACTER VARYING(200) NOT NULL, STARTING_POINT BOOLEAN NOT NULL, JOIN_POINT BOOLEAN NOT NULL, TRANSACTION_BREAK BOOLEAN NOT NULL, TIMEOUT_TIMEXP CHARACTER VARYING(200), SUB_FLOW_CHART BIGINT, PRE_SCRIPT_LANG CHARACTER VARYING(200), POST_SCRIPT_LANG CHARACTER VARYING(200), PRE_SCRIPT TEXT, POST_SCRIPT TEXT, SKIPPABLE SMALLINT NOT NULL, DESCRIPTION TEXT);
CREATE TABLE FLUX_ACTION_RUN (PK BIGINT NOT NULL PRIMARY KEY, NAMESPACE VARCHAR(200) NOT NULL, ACTION_NAME VARCHAR(200), ENTER_TIMESTAMP BIGINT NOT NULL, START_TIMESTAMP BIGINT NOT NULL, EXIT_TIMESTAMP BIGINT NOT NULL, LAST_MODIFIED TIMESTAMP NOT NULL, SUCCESS_STATUS BOOLEAN NOT NULL, PREMATURE BOOLEAN NOT NULL, FLOW_CHART_RUN_FK BIGINT NOT NULL, ACTION_TYPE VARCHAR(200));
CREATE TABLE FLUX_AUDIT_TRAIL (PK SERIAL PRIMARY KEY, ENGINE CHARACTER VARYING(200) NOT NULL, USERNAME CHARACTER VARYING(200), NAMESPACE CHARACTER VARYING(200), EVENT CHARACTER VARYING(200) NOT NULL, CREATION TIMESTAMP NOT NULL, MESSAGE TEXT NOT NULL, ACTION_NAME CHARACTER VARYING(200), FK_RUN_HISTORY_PK BIGINT);
CREATE TABLE FLUX_AUDIT_TRL_TGR(PK BIGINT PRIMARY KEY, ENGINE VARCHAR(200), USERNAME VARCHAR(200), NAMESPACE VARCHAR(200), EVENT VARCHAR(200) NOT NULL, MESSAGE TEXT, ACTION_NAME VARCHAR(200), ACTION_PK BIGINT, EVENT_PK BIGINT, LAST_EVENT_PK BIGINT);
CREATE TABLE FLUX_CLUSTER (PK BIGINT NOT NULL PRIMARY KEY, ENGINE_INSTANCE BIGINT NOT NULL, CURRENT_STATE CHARACTER VARYING(200) NOT NULL, HEARTBEAT BIGINT NOT NULL, NAME CHARACTER VARYING(200) NOT NULL, HOST CHARACTER VARYING(200), PORT INTEGER NOT NULL, IS_SSL BOOLEAN NOT NULL, SCHEDULING BOOLEAN NULL);
CREATE TABLE FLUX_DATA_MAP (PK BIGINT NOT NULL PRIMARY KEY, ACTION BIGINT, FLOW BIGINT, SOURCE_NAME CHARACTER VARYING(200) NOT NULL, SOURCE_TYPE INTEGER NOT NULL, TARGET_NAME CHARACTER VARYING(200) NOT NULL, TARGET_TYPE INTEGER NOT NULL);
CREATE TABLE FLUX_ERROR_RESULT (PK BIGINT NOT NULL PRIMARY KEY, MESSAGE TEXT, CLAZZ CHARACTER VARYING(200) NOT NULL, THROWING_ACTION CHARACTER VARYING(200) NOT NULL, STACK_TRACE TEXT, EXCEPTION_OBJECT BYTEA);
CREATE TABLE FLUX_FLOW (PK BIGINT NOT NULL PRIMARY KEY, TARGET_ACTION BIGINT NOT NULL, SOURCE_ACTION BIGINT NOT NULL, CONDITION CHARACTER VARYING(200));
CREATE TABLE FLUX_FLOW_CHART (PK BIGINT PRIMARY KEY, NAME CHARACTER VARYING(200), SEAL BIGINT NOT NULL, RUN_AS_USER CHARACTER VARYING(200), LISTENER_CLASSPATH CHARACTER VARYING(200), RUN_AS_USER_SOURCE BOOLEAN NOT NULL, IS_TEMPLATE BOOLEAN NOT NULL, DEADLINE_TS TIMESTAMP, DEADLINE_TIMEXP CHARACTER VARYING(200), DEADLINE_WINDOW TIMESTAMP, DEADLINE_WINDOW_TE CHARACTER VARYING(200), DEADLINE_STATUS SMALLINT, CREATION BIGINT NOT NULL, METADATA TEXT, DESCRIPTION TEXT);
CREATE TABLE FLUX_FLOW_CHART_RUN (PK BIGINT NOT NULL PRIMARY KEY, NAMESPACE VARCHAR(200) NOT NULL, ENTER_TIMESTAMP BIGINT NOT NULL, START_TIMESTAMP BIGINT NOT NULL, EXIT_TIMESTAMP BIGINT NOT NULL, LAST_MODIFIED TIMESTAMP NOT NULL, SUCCESS_STATUS BOOLEAN NOT NULL, PREMATURE BOOLEAN NOT NULL);
CREATE TABLE FLUX_FLOW_CHART_TGR (PK BIGINT NOT NULL PRIMARY KEY, NAMESPACE CHARACTER VARYING(200), READY_FK BIGINT NOT NULL);
CREATE TABLE FLUX_FLOW_CONTEXT (PK BIGINT NOT NULL PRIMARY KEY);
CREATE TABLE FLUX_JOINING (PK BIGINT NOT NULL PRIMARY KEY, FLOW BIGINT NOT NULL, READY BIGINT NOT NULL, QUEUE BIGINT NOT NULL, FIRED BOOLEAN NOT NULL);
CREATE TABLE FLUX_LOGGING(PK SERIAL PRIMARY KEY, ENGINE CHARACTER VARYING(200) NOT NULL, USERNAME CHARACTER VARYING(200), NAMESPACE CHARACTER VARYING(200), LOGGER_TYPE CHARACTER VARYING(200) NOT NULL, LOGGING_LEVEL CHARACTER VARYING(200) NOT NULL, CREATION TIMESTAMP NOT NULL, MESSAGE TEXT NOT NULL);
CREATE TABLE FLUX_PERMISSION (PK BIGINT NOT NULL PRIMARY KEY, FK_USER_OR_ROLE_PK BIGINT NOT NULL, NAME CHARACTER VARYING(200) NOT NULL, CONTENT TEXT NOT NULL );
CREATE TABLE FLUX_PK (PK BIGINT NOT NULL PRIMARY KEY, NEXT_PK BIGINT NOT NULL);
CREATE TABLE FLUX_READY (PK BIGINT PRIMARY KEY, NAMESPACE CHARACTER VARYING(200) NOT NULL, FLOW_CHART_NAME CHARACTER VARYING(200) NOT NULL, ACTION BIGINT NOT NULL, EXPEDITED BOOLEAN NOT NULL, FLOW_CONTEXT BIGINT NOT NULL, HEARTBEAT BIGINT NOT NULL, INSTANCE BIGINT, INTERRUPTED BOOLEAN, SEAL BIGINT, SUPER_STATE CHARACTER VARYING(200) NOT NULL, STATE CHARACTER VARYING(200) NOT NULL, RESUME_ACTION BIGINT, RESUME_FLOW_CNTXT BIGINT, FAILED_ERROR BIGINT, EXECUTION_TIME BIGINT, TIMEOUT TIMESTAMP NULL DEFAULT NULL, ORIGINAL_PRIORITY INTEGER, EFFECTIVE_PRIORITY INTEGER, LAST_PRTY_CHANGE BIGINT, PRIORITY_SOURCE BOOLEAN, ERROR_ACTION BIGINT, STATUS CHARACTER VARYING(200), FLOW_CHART_CREATION BIGINT NOT NULL, FLOW_CHART_PK BIGINT NOT NULL, ACTION_NAME CHARACTER VARYING(200) NOT NULL, ENGINE CHARACTER VARYING(200), ACTION_DESCRIPTION TEXT, FLOW_CHART_DESCRIPTION TEXT, DEADLINE_TS TIMESTAMP, DEADLINE_STATUS SMALLINT, ACTION_TYPE VARCHAR(200));
CREATE TABLE FLUX_REPOSITORY (PK SERIAL PRIMARY KEY, NAMESPACE CHARACTER VARYING(200) NOT NULL UNIQUE, CONTENT TEXT NOT NULL, DESCRIPTION TEXT, OWNER BIGINT, CREATION TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, LAST_MODIFIED TIMESTAMP NOT NULL, TYPE SMALLINT NOT NULL);
CREATE TABLE FLUX_ROLE (PK BIGINT NOT NULL PRIMARY KEY, NAME CHARACTER VARYING(200) NOT NULL, DESCRIPTION CHARACTER VARYING(200));
CREATE TABLE FLUX_RUN_AVERAGE (NAMESPACE CHARACTER VARYING(200) NOT NULL, START_TIMESTAMP BIGINT NOT NULL, END_TIMESTAMP BIGINT NOT NULL, AVERAGE_RUN_TIME BIGINT NOT NULL, AVERAGE_WAIT_TIME BIGINT NOT NULL, FIRING_COUNT BIGINT NOT NULL, LAST_MODIFIED TIMESTAMP NOT NULL, UNIQUE(NAMESPACE));
CREATE TABLE FLUX_SIGNAL (PK BIGINT NOT NULL PRIMARY KEY, MONITOR BIGINT, RAISE BIGINT, CLEAR BIGINT, RAISED BIGINT, NAME CHARACTER VARYING(200) NOT NULL);
CREATE TABLE FLUX_TIMER_TRIGGER (PK BIGINT NOT NULL PRIMARY KEY, LATE_TIME_WINDOW CHARACTER VARYING(200), SCHEDULED_T_DATE BIGINT NOT NULL, END_DATE BIGINT NOT NULL, END_TIME_EXP CHARACTER VARYING(200), TOTAL_COUNT BIGINT NOT NULL, REMAINING_COUNT BIGINT NOT NULL, ACTUAL_T_DATE BIGINT NOT NULL, ABSTRACT_TIMEXP BIGINT, MAKEUP_FIRING BOOLEAN NOT NULL);
CREATE TABLE FLUX_USER (PK BIGINT NOT NULL PRIMARY KEY, USERNAME CHARACTER VARYING(200) NOT NULL, PASSWORD CHARACTER VARYING(200) NOT NULL, DISPLAY_NAME CHARACTER VARYING(200), UNIQUE(USERNAME));
CREATE TABLE FLUX_USER_ROLE_REL (PK BIGINT PRIMARY KEY, FK_USER_PK BIGINT NOT NULL, FK_ROLE_PK BIGINT NOT NULL);
CREATE TABLE FLUX_VARIABLE (PK BIGINT NOT NULL PRIMARY KEY, OWNER BIGINT, TYPE CHARACTER VARYING(200) NOT NULL, NAME CHARACTER VARYING(200), CONTENT TEXT, FK_TYPE_PK BIGINT);

CREATE INDEX FLUX_ACTION1 ON FLUX_ACTION(FLOW_CHART);

CREATE INDEX FLUX_AUDIT_TRAIL1 ON FLUX_AUDIT_TRAIL(CREATION);
CREATE INDEX FLUX_AUDIT_TRAIL2 ON FLUX_AUDIT_TRAIL(NAMESPACE);
CREATE INDEX FLUX_AUDIT_TRAIL3 ON FLUX_AUDIT_TRAIL(ACTION_NAME);
CREATE INDEX FLUX_AUDIT_TRAIL4 on FLUX_AUDIT_TRAIL(EVENT);
CREATE INDEX FLUX_AUDIT_TRAIL5 on FLUX_AUDIT_TRAIL(USERNAME);

CREATE INDEX FLUX_AUDIT_TGR1 ON FLUX_AUDIT_TRL_TGR(ENGINE);
CREATE INDEX FLUX_AUDIT_TGR2 ON FLUX_AUDIT_TRL_TGR(NAMESPACE);
CREATE INDEX FLUX_AUDIT_TGR3 ON FLUX_AUDIT_TRL_TGR(ACTION_NAME);
CREATE INDEX FLUX_AUDIT_TGR4 on FLUX_AUDIT_TRL_TGR(EVENT);
CREATE INDEX FLUX_AUDIT_TGR5 on FLUX_AUDIT_TRL_TGR(USERNAME);
CREATE INDEX FLUX_AUDIT_TGR7 on FLUX_AUDIT_TRL_TGR(MESSAGE);
CREATE INDEX FLUX_AUDIT_TGR8 on FLUX_AUDIT_TRL_TGR(ACTION_PK);

CREATE INDEX FLUX_RUN_AVERAGE1 ON FLUX_RUN_AVERAGE(LAST_MODIFIED);

CREATE INDEX FLUX_ACTION_RUN1 ON FLUX_ACTION_RUN(LAST_MODIFIED);
CREATE INDEX FLUX_ACTION_RUN2 ON FLUX_ACTION_RUN(NAMESPACE);
CREATE INDEX FLUX_ACTION_RUN3 ON FLUX_ACTION_RUN(FLOW_CHART_RUN_FK);
CREATE INDEX FLUX_ACTION_RUN4 ON FLUX_ACTION_RUN(START_TIMESTAMP);
CREATE INDEX FLUX_ACTION_RUN5 ON FLUX_ACTION_RUN(EXIT_TIMESTAMP);

CREATE INDEX FLUX_FLOW_CHART_RUN1 ON FLUX_FLOW_CHART_RUN(LAST_MODIFIED);
CREATE INDEX FLUX_FLOW_CHART_RUN2 ON FLUX_FLOW_CHART_RUN(NAMESPACE);

CREATE INDEX FLUX_READY1 ON FLUX_READY(ACTION);
CREATE INDEX FLUX_READY2 ON FLUX_READY(SEAL);
CREATE INDEX FLUX_READY3 ON FLUX_READY(STATE);
CREATE INDEX FLUX_READY4 ON FLUX_READY(HEARTBEAT);
CREATE INDEX FLUX_READY5 ON FLUX_READY(FLOW_CHART_NAME);
CREATE INDEX FLUX_READY6 ON FLUX_READY(EXECUTION_TIME);
CREATE INDEX FLUX_READY7 ON FLUX_READY(TIMEOUT);

CREATE INDEX FLUX_SIGNAL1 ON FLUX_SIGNAL(RAISED);
CREATE INDEX FLUX_SIGNAL2 ON FLUX_SIGNAL(NAME);

CREATE INDEX FLUX_VARIABLE1 ON FLUX_VARIABLE(OWNER);
CREATE INDEX FLUX_VARIABLE2 ON FLUX_VARIABLE(FK_TYPE_PK);
CREATE INDEX FLUX_VARIABLE3 ON FLUX_VARIABLE(NAME);

CREATE INDEX FLUX_FLOW1 ON FLUX_FLOW(SOURCE_ACTION);
CREATE INDEX FLUX_FLOW2 ON FLUX_FLOW(TARGET_ACTION);

CREATE INDEX FLUX_FLOW_CHART1 ON FLUX_FLOW_CHART(SEAL);
CREATE INDEX FLUX_FLOW_CHART2 ON FLUX_FLOW_CHART(NAME);
CREATE INDEX FLUX_FLOW_CHART3 ON FLUX_FLOW_CHART(CREATION);


CREATE INDEX FLUX_FLOW_CHART_TGR1 ON FLUX_FLOW_CHART_TGR(NAMESPACE);

CREATE INDEX FLUX_USER1 on FLUX_USER(USERNAME);

CREATE INDEX FLUX_ROLE1 on FLUX_ROLE(NAME);

CREATE INDEX FLUX_USR_ROL_RELATION1 on FLUX_USER_ROLE_REL(FK_USER_PK);
CREATE INDEX FLUX_USR_ROL_RELATION2 on FLUX_USER_ROLE_REL(FK_ROLE_PK);

CREATE INDEX FLUX_PERMISSION1 on FLUX_PERMISSION(FK_USER_OR_ROLE_PK);

CREATE INDEX FLUX_LOGGING1 on FLUX_LOGGING(CREATION);
CREATE INDEX FLUX_LOGGING2 on FLUX_LOGGING(NAMESPACE);
CREATE INDEX FLUX_LOGGING3 on FLUX_LOGGING(USERNAME);
CREATE INDEX FLUX_LOGGING5 on FLUX_LOGGING(ENGINE);
CREATE INDEX FLUX_LOGGING6 on FLUX_LOGGING(LOGGER_TYPE);
CREATE INDEX FLUX_LOGGING7 on FLUX_LOGGING(LOGGING_LEVEL);

CREATE INDEX FLUX_JOINING1 ON FLUX_JOINING(READY);
CREATE INDEX FLUX_JOINING2 ON FLUX_JOINING(FLOW);

CREATE INDEX FLUX_DATA_MAP1 ON FLUX_DATA_MAP(ACTION);
CREATE INDEX FLUX_DATA_MAP2 ON FLUX_DATA_MAP(FLOW);
